on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Selecion o ambiente"
        type: choice
        required: true
        default: dev
        options:
          - alpha
          - dev
          - prod

      need_build_android:
        description: "Build Android?"
        type: boolean
        default: true

      need_build_ios:
        description: "Build iOS?"
        type: boolean
        default: true

      need_build_web:
        description: "Build Web?"
        type: boolean
        default: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show Environment
        run: echo "Environment: ${{ inputs.environment }}"
      - name: Show Build Android
        run: echo "Build Android: ${{ inputs.need_build_android }}"
      - name: Show Build iOS
        run: echo "Build iOS: ${{ inputs.need_build_ios }}"
      - name: Show Build Web
        run: echo "Build Web: ${{ inputs.need_build_web }}"
     

     