name: Reusable • Build Android

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        type: choice
        required: true
        default: dev
        options: [Alpha, Dev, Prod]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Build Android (${{ inputs.flavor }})
        run: echo "Build Android "
