on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Selecione o ambiente"
        type: choice
        required: true
        default: dev
        options: [alpha, dev, prod]
      need_build_android:
        description: "Build Android?"
        type: boolean
        default: true
      need_build_ios:
        description: "Build iOS?"
        type: boolean
        default: true
      need_build_web:
        description: "Build Web?"
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      NEED_BUILD_ANDROID: ${{ github.event.inputs.need_build_android }}
      NEED_BUILD_IOS: ${{ github.event.inputs.need_build_ios }}
      NEED_BUILD_WEB: ${{ github.event.inputs.need_build_web }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show inputs
        run: |
          echo "Environment: $ENVIRONMENT"
          echo "Build Android: $NEED_BUILD_ANDROID"
          echo "Build iOS: $NEED_BUILD_IOS"
          echo "Build Web: $NEED_BUILD_WEB"

      - name: Build Android
        if: ${{ fromJSON(github.event.inputs.need_build_android) }}
        run: echo "Rodando build Android..."

      - name: Build iOS
        if: ${{ fromJSON(github.event.inputs.need_build_ios) }}
        run: echo "Rodando build iOS..."

      - name: Build Web
        if: ${{ fromJSON(github.event.inputs.need_build_web) }}
        run: echo "Rodando build Web..."
